### ISSUE TITLE
Reduce Storage Space does not delete Audit Logs

### ISSUE THREAD

**Issue by DVilarrubias** [tech-quantum/XrmToolBoxPlugins#22]
In "Reduce Storage Space Usage" delete audit logs, for example older than 1 month, does not take effect.
Throws an alert with message "entity name":
![image](https://user-images.githubusercontent.com/51156511/58548159-13cc8d80-8209-11e9-908b-693505590abf.png)

Maybe a Bulk Delete Job cannot run on audit logs..

Best.

**Comment by deepakkumar1984** [comment]
I will check the issue. Haven't tested the tool for a long time

**Comment by DVilarrubias** [comment]
Thank you!

**Comment by deepakkumar1984** [comment]
Latest CRM version probably from 9 and above doesn't have the audit entity which was used to initiate the bulk deletion job. I will try to find an alternate solution to automate that, otherwise may have to remove the option altogether :(

**Comment by deepakkumar1984** [comment]
No longer supporting audit logs. Removed the options from plugin interface
